#ifndef BBPROJECTMANAGER_GLOBAL_HPP_INCLUDED
#define BBPROJECTMANAGER_GLOBAL_HPP_INCLUDED

#include <QtGlobal>

#if defined(BOOSTBUILDPROJECTMANAGER_LIBRARY)
#  define BOOSTBUILDPROJECTMANAGER_EXPORT Q_DECL_EXPORT
#else
#  define BOOSTBUILDPROJECTMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // BBPROJECTMANAGER_GLOBAL_HPP_INCLUDED
