#ifndef BOOSTBUILD_GLOBAL_HPP
#define BOOSTBUILD_GLOBAL_HPP

#include <QtGlobal>

#if defined(BOOSTBUILD_LIBRARY)
#  define BOOSTBUILDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BOOSTBUILDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BOOSTBUILD_GLOBAL_HPP
